version: 2
updates:
  - package-ecosystem: "docker"
    directory: "/predbat"
    schedule:
      interval: "weekly"
    groups:
      docker-base:
        patterns: ["*"]

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      github-actions:
        patterns: ["*"]