ARG BASE_IMAGE="python:3.13-slim-bookworm"

# -------------------------------------------------
# Python deps builder
# -------------------------------------------------
FROM ${BASE_IMAGE} AS builder
WORKDIR /install

COPY requirements.txt /

# hadolint ignore=DL3008
RUN set -eux; \
    apt-get update; \
    apt-get install --yes --no-install-recommends gcc g++ libffi-dev; \
    pip install --no-cache-dir --prefix=/install -r /requirements.txt

# -------------------------------------------------
# s6-overlay builder
# -------------------------------------------------
FROM ${BASE_IMAGE} AS s6-builder

ARG S6_VERSION=v3.2.2.0
ARG TARGETARCH

WORKDIR /tmp/s6

# hadolint ignore=DL3008
RUN apt-get update \
 && apt-get install -y --no-install-recommends ca-certificates xz-utils

ADD https://github.com/just-containers/s6-overlay/releases/download/${S6_VERSION}/s6-overlay-noarch.tar.xz .
ADD https://github.com/just-containers/s6-overlay/releases/download/${S6_VERSION}/s6-overlay-x86_64.tar.xz s6-overlay-amd64.tar.xz
ADD https://github.com/just-containers/s6-overlay/releases/download/${S6_VERSION}/s6-overlay-aarch64.tar.xz s6-overlay-arm64.tar.xz
ADD https://github.com/just-containers/s6-overlay/releases/download/${S6_VERSION}/s6-overlay-arm.tar.xz s6-overlay-arm.tar.xz

RUN set -eux; \
    mkdir -p /s6-root; \
    tar -C /s6-root -Jxpf s6-overlay-noarch.tar.xz; \
    case "${TARGETARCH}" in \
      amd64) tar -C /s6-root -Jxpf s6-overlay-amd64.tar.xz ;; \
      arm64) tar -C /s6-root -Jxpf s6-overlay-arm64.tar.xz ;; \
      arm)   tar -C /s6-root -Jxpf s6-overlay-arm.tar.xz ;; \
      *) echo "Unsupported architecture: ${TARGETARCH}" && exit 1 ;; \
    esac

# -------------------------------------------------
# Final runtime stage
# -------------------------------------------------
FROM ${BASE_IMAGE}

ARG USER_NAME="predbat"
ARG USER_GROUP="predbat"
ARG UID="9005"
ARG GID="9005"
ARG PREDBAT_VERSION
ARG BASE_IMAGE
ARG BUILD_DATE
ARG ADDON_VERSION

WORKDIR /config
# hadolint ignore=DL3002
USER root

# hadolint ignore=DL3008
RUN set -eux; \
    apt-get update; \
    apt-get install -y --no-install-recommends netcat-openbsd ca-certificates; \
    groupadd -g ${GID} ${USER_GROUP}; \
    useradd -l -u ${UID} -g ${GID} -m -s /bin/bash ${USER_NAME}; \
    chown -R ${USER_NAME} /config; \
    apt-get clean; \
    rm -rf /var/lib/apt/lists/*

# s6-overlay
COPY --from=s6-builder /s6-root/ /
COPY --from=builder /install /usr/local/

# App files - Predbat itself is fetched straight from GitHub, never vendored
ADD --chown=${USER_NAME} \
  https://github.com/springfall2008/batpred.git#$PREDBAT_VERSION:apps/predbat/ \
  https://github.com/springfall2008/batpred.git#$PREDBAT_VERSION:apps/predbat/config/ \
  /addon/
COPY --chown=${USER_NAME} rootfs/alpine/* /addon/

COPY rootfs/docker/s6-rc/ /etc/s6-overlay/s6-rc.d/

# Define build arguments and labels
LABEL \
    io.hass.type="addon" \
    addon.version=${ADDON_VERSION} \
    maintainer="nipar4 (https://github.com/nipar4/predbat_addon)" \
    org.opencontainers.image.vendor="Springfall2008" \
    org.opencontainers.image.authors="springfall2008, nipar4" \
    org.opencontainers.image.licenses="MIT" \
    org.opencontainers.image.url="https://github.com/springfall2008, https://github.com/nipar4/predbat_addon" \
    org.opencontainers.image.source="https://github.com/nipar4/predbat_addon" \
    org.opencontainers.image.documentation="https://github.com/springfall2008/predbat_addon/blob/main/predbat/DOCS.md" \
    org.opencontainers.image.created=${BUILD_DATE} \
    org.opencontainers.image.title="Predbat Addon Docker version" \
    org.opencontainers.image.base.digest=${BASE_IMAGE} \
    org.opencontainers.image.version=${PREDBAT_VERSION}
ENTRYPOINT ["/init"]
