name: Lint Workflows

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/*.yml'

jobs:
  actionlint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Run actionlint
        run: |
          bash <(curl -s https://raw.githubusercontent.com/rhysd/actionlint/main/scripts/download-actionlint.bash)
          ./actionlint .github/workflows/sync-predbat.yml .github/workflows/sync-addon.yml